### ISSUE TITLE
Multiple data logger using pic18f16q41

### ISSUE THREAD

**Issue by sayali234** [microchip-pic-avr-examples/pic18f16q41-curiosity-lpc-demo-code#1]
In my application the circuit will be in field for some duration e.g 8 to 10 days or or more than that , in field the PIC18F16Q41 will store the result of count value and after some days when we connect PIC18F16Q41  to laptop or PC we will able to read that store result. now what is happening when I run the program the count value is 3 and I disconnect the evaluation board and again when I connect the board and read the memory it showing 3 but when I again disconnect and read eeprom memory it shows zero count value.

I want to use this kit as data logger , please suggest what changes I need to make in  program. Do I need to change memory type.

Below is snapshot of my code.

#define EEAddr 0x0001 //EEPROM starting address
double count = 0;
double display = 0;

DATAEE_WriteByte(EEAddr, count);
display = DATAEE_ReadByte(EEAddr);

printf("display : %f \r\n",display);

Again is it possible to read and write more than one data in eeprom. I tried with below code to read and write two data but it is showing error.

 DATAEE_WriteByte1(EEAddr, count);

 display = DATAEE_ReadByte(EEAddr);

  

  DATAEE_WriteByte1(EEAddr1,count1);

 display1 = DATAEE_ReadByte1(EEAddr1);

**Comment by pic-avr-github-admin** [comment]
Hi @sayali234 ,
I don't have enough information to give you a full answer, but you should be able to read/write multiple bytes. I would make sure EEAddr1 is being set to a different address than EEAddr, verify EEAddr1 is a valid memory address, and check for an error code in NVMCON1 to see if the write failed.
